### ISSUE TITLE
Minimum Player Votekick

### ISSUE THREAD

**Issue by my3t** [TitanTF/Issue-Tracking#51]
We have received reports of players being vote kicked after only a minimum of 1 vote was required.

![20210722_174057](https://user-images.githubusercontent.com/33184869/135097907-c2e63e1a-e213-4635-ac72-1a10aae42e36.png)

**Comment by Lecubon1** [comment]
Seems to be related to the case where the players are abusing votekick system by simply 1 vote

**Comment by my3t** [comment]
A fix has been released for this.
